In [4]:
####This code does the one hot encoding for five existing features.
import pandas as pd
df = pd.read_csv("E:\\jup\\Trainset.csv")

dummies = pd.get_dummies(df.Month)
merged1 = pd.concat([df,dummies],axis='columns')
final1 = merged1.drop(['Month'],axis='columns')


dummies_province = pd.get_dummies(final1.Province)
#dummies_province_dropped = dummies_province.drop([9],axis='columns')
merged2 = pd.concat([final1,dummies_province_dropped],axis='columns')
final2 = merged2.drop(['Province'],axis='columns')


dummies_browser = pd.get_dummies(final2.Browser)
#dummies_browser_dropped = dummies_browser.drop([1],axis='columns')
merged3 = pd.concat([final2,dummies_browser_dropped],axis='columns')
final3 = merged3.drop(['Browser'],axis='columns')


dummies_operatingSystems = pd.get_dummies(final3.OperatingSystems)
#dummies_operatingSystems_dropped = dummies_operatingSystems.drop([1],axis='columns')
merged4 = pd.concat([final3,dummies_operatingSystems_dropped],axis='columns')
final4 = merged4.drop(['OperatingSystems'],axis='columns')

dummies_VisitorType = pd.get_dummies(final4.VisitorType)
#dummies_VisitorType_dropped = dummies_VisitorType.drop(['Other'],axis='columns')
merged5 = pd.concat([final4,dummies_VisitorType_dropped],axis='columns')
final5 = merged5.drop(['VisitorType'],axis='columns')

print(final5.shape)

f=pd.DataFrame(final5)
f.to_csv('E:\\jup\\sample_Traintest.csv',index=False)

FileNotFoundError: [Errno 2] File b'E:\\jup\\Trainset.csv' does not exist: b'E:\\jup\\Trainset.csv'

In [7]:
####This code does the one hot encoding for five existing features.
import pandas as pd
df = pd.read_csv("E:\\jup\\Trainset.csv")

dummies = pd.get_dummies(df.Month)
merged1 = pd.concat([df,dummies],axis='columns')
final1 = merged1.drop(['Month'],axis='columns')


dummies_province = pd.get_dummies(final1.Province)

merged2 = pd.concat([final1,dummies_province],axis='columns')
final2 = merged2.drop(['Province'],axis='columns')


dummies_browser = pd.get_dummies(final2.Browser)

merged3 = pd.concat([final2,dummies_browser],axis='columns')
final3 = merged3.drop(['Browser'],axis='columns')


dummies_operatingSystems = pd.get_dummies(final3.OperatingSystems)

merged4 = pd.concat([final3,dummies_operatingSystems],axis='columns')
final4 = merged4.drop(['OperatingSystems'],axis='columns')

dummies_VisitorType = pd.get_dummies(final4.VisitorType)

merged5 = pd.concat([final4,dummies_VisitorType],axis='columns')
final5 = merged5.drop(['VisitorType'],axis='columns')

print(final5.shape)

f=pd.DataFrame(final5)
f.to_csv('E:\jup\sample_Trainset.csv',index=False,)

(10480, 56)


In [2]:
################This code print the sizes of the data set

import pandas as pd
df = pd.read_csv("E:\\hackstat\\jup1\\Trainset.csv")
print(df.shape)

(10466, 57)


In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import math as ma

import os
for dirname, _, filenames in os.walk('/kaggle/input/'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [16]:
"""We have done few changes to the features of(some dropped) trainset and xtest files according to the one hot 
   encoding and correlation heatmap. Therefore this code creates the submission file according to exsiting
   trainset and xtest file under random forest model.
"""

from sklearn.ensemble import RandomForestClassifier

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

#Trainset = pd.read_csv("/kaggle/input/hackstat2k19/Trainset.csv", header = 0) 
Trainset = pd.read_csv("E:\\jup\\Trainset.csv", header = 0)
Trainset = Trainset.dropna()

sampleset = pd.read_csv("E:\\jup\\sample_submisison.csv", header = 0) 
sampleset = sampleset.dropna()

xset = pd.read_csv("E:\\jup\\xtest.csv")
xset = xset.dropna()

#Trainset['is_train'] = np.random.uniform(0,1,len(Trainset)) <= 0.75
print(Trainset)

Train, Test = Trainset,xset

print('Number of Training examples', len(Train))
print('Number of Testing examples', len(Test))

features = Trainset.columns[:30]
print(features)
y = Train['Revenue']
y

id_ = sampleset['ID']
#new_ = id_.DataFarame(id_)
clf = RandomForestClassifier(n_estimators = 30, n_jobs = 2, random_state = 0)
clf.fit(Train[features],y)

preds = clf.predict(Test[features])

#print(tpe(new_))
#print(type(preds))
YArray= id_.as_matrix(columns=None)
print (YArray)

df = pd.DataFrame({"ID" : YArray, "Revenue" : preds})
df.to_csv("E:\\jup\\submission.csv", index=False)
#dfObj = pd.DataFrame(YArray,preds,columns = ["ID","Revenue"]) 

#dfObj.to_csv('submit.csv', index = False)

#pd.crosstab(Test['Revenue'], preds, rownames = ['Actual Revenue'], colnames = ['Predicted Revenue'])
#Test['Revenue']
#X, y = Trainset.iloc[:, :16], Trainset.iloc[:, 17]

#Xset = xset.iloc[:, :16]
#print(X)
#print(y)

#clf = RandomForestClassifier(n_estimators=10)
#clf = clf.fit(X, y)
#clf

#clf = RandomForestClassifier(n_estimators=17, max_depth=None,min_samples_split=2, random_state=0)
#scores = cross_val_score(clf, X, y, cv=5)
#scores.mean() 

       Homepage _Duration  Aboutus_Duration  Contactus  BounceRates  \
0               10.000000              0.00        9.0     0.000000   
1               15.000000              0.00       10.0     0.000000   
2               85.000000              0.00       14.0     0.000000   
3              175.100000              0.00       26.0     0.000000   
4               25.000000              0.00        5.0     0.066667   
5              113.750000              0.00       26.0     0.022667   
6                0.000000              0.00       53.0     0.009804   
7              102.866667            339.50       29.0     0.000000   
8               49.300000              0.00       12.0     0.000000   
9                8.000000              0.00       47.0     0.010417   
10               0.000000              0.00       26.0     0.015385   
11             210.500000              0.00       26.0     0.017241   
12               0.000000              0.00       10.0     0.000000   
13    

C:\Users\User\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


[   1    2    3 ... 1848 1849 1850]


C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


In [5]:
import pandas as pd
df = pd.read_csv("E:\\jup\\xtest.csv")

fi=pd.DataFrame(df)
fi.to_csv('E:\\jup\\xtestV1.csv',index=False,)

In [2]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import math as ma
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

import os
#for dirname, _, filenames in os.walk('/kaggle/input/'):
 #   for filename in filenames:
  #      print(os.path.join(dirname, filename))

Trainset1 = pd.read_csv("E:\\sample\\Trainset.csv", header = 0) 
Trainset1 = Trainset1.dropna()

sampleset = pd.read_csv("E:\\sample\\sample_submisison.csv", header = 0) 
sampleset = sampleset.dropna()

dummies1 = pd.get_dummies(Trainset1.Month)
dummies1 = dummies1.drop(['Feb'], axis = 'columns')
merged1 = pd.concat([Trainset1,dummies1],axis = 'columns')

dummies2 = pd.get_dummies(merged1.VisitorType)
dummies2 = dummies2.drop(['Other'], axis = 'columns')
merged2 = pd.concat([merged1,dummies2],axis = 'columns')

dummies3 = pd.get_dummies(merged2.OperatingSystems)
dummies3 = dummies3.drop([1], axis = 'columns')
merged3 = pd.concat([merged2,dummies3],axis = 'columns')

dummies4 = pd.get_dummies(merged3.Browser)
dummies4 = dummies4.drop([1], axis = 'columns')
merged4 = pd.concat([merged3,dummies4],axis = 'columns')

dummies5 = pd.get_dummies(merged4.Province)
dummies5 = dummies5.drop([1], axis = 'columns')
merged5 = pd.concat([merged4,dummies5],axis = 'columns')

y = merged5['Revenue']
##y = y.iloc[0:300]
Trainset = merged5.drop(['Month','VisitorType','Weekend','OperatingSystems','Browser','Province','Revenue'], axis = 'columns')
X=Trainset
xset1 = pd.read_csv("E:\\sample\\xtest.csv")
xset1 = xset1.dropna()

xdummies1 = pd.get_dummies(xset1.Month)
# xdummies1 = xdummies1.drop(['Feb'], axis = 'columns')
xmerged1 = pd.concat([xset1,xdummies1],axis = 'columns')

xdummies2 = pd.get_dummies(xmerged1.VisitorType)
# xdummies2 = xdummies2.drop(['Other'], axis = 'columns')
xmerged2 = pd.concat([xmerged1,xdummies2],axis = 'columns')

xdummies3 = pd.get_dummies(xmerged2.OperatingSystems)
# xdummies3 = xdummies3.drop([1], axis = 'columns')
xmerged3 = pd.concat([xmerged2,xdummies3],axis = 'columns')

xdummies4 = pd.get_dummies(xmerged3.Browser)
#xdummies4 = xdummies4.drop([1], axis = 'columns')
xmerged4 = pd.concat([xmerged3,xdummies4],axis = 'columns')

xdummies5 = pd.get_dummies(xmerged4.Province)
#xdummies5 = xdummies5.drop([1], axis = 'columns')
xmerged5 = pd.concat([xmerged4,xdummies5],axis = 'columns')
# X = xmerged5.drop(['Month','VisitorType','Weekend','OperatingSystems','Browser','Province'], axis = 'columns').iloc[0:300]

# Train = Trainset,xset
# Test = xset
# print('Number of Training examples', len(Train))
# print('Number of Testing examples', len(Test))

# features = Train.columns[:37]
# print(features)
#y = Train['Revenue']


# id_ = sampleset['ID']
# #new_ = id_.DataFarame(id_)
# clf = RandomForestClassifier(n_jobs = 2, random_state = 0)
# clf.fit(Train[features],y)

# clf.predict(Test[features])

# print(Test[features])

# preds = clf.predict(Test[features])

# YArray= id_.as_matrix(columns=None)
# print (YArray)

# df = pd.DataFrame({"ID" : YArray, "Revenue" : preds})
# df.to_csv("submission.csv", index=False)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)
# svclassifier = SVC(kernel='rbf')
# svclassifier.fit(X_train, y_train)
print(X)
print(y)
y_pred = svclassifier.predict(X_test)
print(y_pred)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))





       Homepage  Homepage _Duration  Aboutus  Aboutus_Duration  Contactus  \
0           1.0           10.000000      0.0              0.00        9.0   
1           2.0           15.000000      0.0              0.00       10.0   
2           1.0           85.000000      0.0              0.00       14.0   
3           5.0          175.100000      0.0              0.00       26.0   
4           2.0           25.000000      0.0              0.00        5.0   
5           1.0          113.750000      0.0              0.00       26.0   
6           0.0            0.000000      0.0              0.00       53.0   
7           9.0          102.866667      3.0            339.50       29.0   
8           4.0           49.300000      0.0              0.00       12.0   
9           1.0            8.000000      0.0              0.00       47.0   
10          0.0            0.000000      0.0              0.00       26.0   
11          6.0          210.500000      0.0              0.00       26.0   

[0 1 0 ... 0 0 1]
[[1724   46]
 [ 191  133]]
              precision    recall  f1-score   support

           0       0.90      0.97      0.94      1770
           1       0.74      0.41      0.53       324

    accuracy                           0.89      2094
   macro avg       0.82      0.69      0.73      2094
weighted avg       0.88      0.89      0.87      2094

